### ISSUE TITLE
Grey Screen

### ISSUE THREAD

**Issue by Instatic** [pncuong23/dell-vostro-5468#2]
Install Big Sur on my other Hackintosh, and copy in the hidden EFI folder, after loader / booting the installer get a grey screen with cursor i5 7200U CPU ...
Any idea ?

by the was is this for Big Sur ?

**Comment by Instatic** [comment]
maybe some wrong bios settings ?

**Comment by pncuong23** [comment]
You can use tool corpnewt/GenSMBIOS to genaral news  SMBIOS.

**Comment by Instatic** [comment]
I change in windows my GenSMBIOS with the tool to MacBookPro14,1 and 14,2 both don't run seems also to be another issue...
now almost got to the install ... 
put the the end it ends up with an Error window "The MacOS installation couldn't be completed." also freeze 

![WhatsApp Image 2021-05-16 at 12 03 24](https://user-images.githubusercontent.com/31675419/118393339-f20b8180-b63e-11eb-8b53-a155d6ad37d9.jpeg)

it runs really long time, until I saw the loading bar ... then this happens :(

**Comment by Instatic** [comment]
I'm now on Catalina 
[Installer Log 16-May-2021.txt](https://github.com/pncuong23/dell-vostro-5468/files/6489091/Installer.Log.16-May-2021.txt)

**Comment by pncuong23** [comment]
You can updated new version, OpenCore 0.6.9 and new kext

Trân trọng

------

Phan Nguyễn Cường

0936.167.151

***@***.***

**Comment by Instatic** [comment]
it is maybe a hardware problem ? it doesn't matter which OS Big Sur and Catalina some issues ... tried also many others EFIs crazy

**Comment by Instatic** [comment]
now anythings works almost fine ... accept the trackpad ...,
Ethernet also not work weird

**Comment by lurepheonix** [comment]
> now anythings works almost fine

Can you tell how you bypassed that "can not be installed" error? Having the same error, still haven't found a way to fix it.
